version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Путь к директории с фронтендом
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app:delegated  # Оптимизация синхронизации
    env_file:
      - ./frontend/.env
    working_dir: /app
    command: ./wait-for-it.sh api:8000 -- npm install && npm start  # Ожидание API
    depends_on:
      - api

  api:
    build:
      context: ./api  # Путь к директории с бэкендом
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app:delegated  # Оптимизация синхронизации
    env_file:
      - ./api/.env
    working_dir: /app
    command: npm install && npm run start
