version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Путь к директории с фронтендом
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    working_dir: /app
    command: npm install && npm start
    depends_on:
      - api

  api:
    build:
      context: ./api  # Путь к директории с бэкендом
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    env_file:
      - .env
    working_dir: /app
    command: npm install && npm run start
